version: "3.5"
services:
  node:
    image: "node.hopr.public.dappnode.eth:1.0.8"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.93.4
    ports:
      - "9091:9091/tcp"
      - "9091:9091/udp"
      - "3001"
    volumes:
      - "db:/app/hoprd-db"
    environment:
      - DEBUG=hopr*
      - HOPRD_ENVIRONMENT=monte_rosa
      - "HOPRD_HOST=0.0.0.0:9091"
      - HOPRD_ANNOUNCE=false
      - HOPRD_API=true
      - HOPRD_API_HOST=0.0.0.0
      - HOPRD_API_PORT=3001
      - HOPRD_HEALTH_CHECK=true
      - HOPRD_HEALTH_CHECK_HOST=0.0.0.0
      - HOPRD_HEALTH_CHECK_PORT=8080
      - HOPRD_PASSWORD=open-sesame-iTwnsPNg0hpagP+o6T0KOwiH9RQ0
      - HOPRD_API_TOKEN=!5qxc9Lp1BE7IFQ-nrtttU
      - HOPRD_DISABLE_API_AUTHENTICATION=true
      - HOPRD_IDENTITY=/app/hoprd-db/.hopr-identity
      - HOPRD_DATA=/app/hoprd-db/data
      - HOPRD_INIT=true
      - HOPRD_ALLOW_PRIVATE_NODE_CONNECTIONS=false
      - "HOPRD_PROVIDER=https://provider-proxy.hoprnet.workers.dev/xdai_mainnet"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
  admin:
    image: "gcr.io/hoprassociation/hopr-admin:bratislava"
    ports:
      - "3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
volumes:
  db: {}
